# Module Name and Block layout configuration: Point
module-name: Point
blocks:
  - id: block2
    length: 83,35cm
    main:
      - seg6
    overlaps:
      - seg5
      - seg7
    is_reversed: false
    direction: bidirectional
    signals:
      - signal3
      - signal4
  - id: block3
    length: 79,45cm
    main:
      - seg2
    overlaps:
      - seg1
      - seg3
    is_reversed: false
    direction: bidirectional
    signals:
      - signal1
      - signal2
  - id: block4
    length: 72,15cm
    main:
      - seg15
    overlaps:
      - seg14
      - seg16
    is_reversed: false
    direction: bidirectional
    signals:
      - signal7
      - signal8
platforms:
reversers:
crossings:
signal-types:
  - id: entry
    aspects:
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: exit
    aspects:
      - aspect_shunt
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: distant
    aspects:
      - aspect_caution
      - aspect_go
      - aspect_stop
  - id: block
    aspects:
      - aspect_go
      - aspect_stop
  - id: shunting
    aspects:
      - aspect_shunt
      - aspect_stop
  - id: halt
    aspects:
      - aspect_stop
  - id: platformlight
    aspects:
      - high
      - low
compositions:
peripheral-types:
  - id: onebit
    aspects:
      - high
      - low
