# Interlocking table
interlocking-table:
  - id: 0 #route0
    source: signal10
    destination: signal8
    orientation: anticlockwise
    path:
      # point6.normal -> block4
      - id: seg21
      - id: seg14
      - id: seg15
      - id: seg16
    sections:
      - id: block4
    length: 83,05cm
    signals:
      - id: signal10
      - id: signal8
    points:
      - id: point6
        position: normal
    conflicts:
      - id: 1
      - id: 5
      - id: 7
  - id: 1 #route1
    source: signal10
    destination: signal12
    orientation: anticlockwise
    path:
      # point6.reverse -> block6
      - id: seg21
      - id: seg23
      - id: seg24
      - id: seg25
    sections:
      - id: block6
    length: 73,90cm
    signals:
      - id: signal10
      - id: signal12
    points:
      - id: point6
        position: reverse
    conflicts:
      - id: 0
      - id: 5
      - id: 7
  - id: 2 #route2
    source: signal4
    destination: signal10
    orientation: anticlockwise
    path:
      # point2.reverse -> block1
      - id: seg8
      - id: seg18
      - id: seg19
      - id: seg20
    sections:
      - id: block1
    length: 84,20cm
    signals:
      - id: signal4
      - id: signal10
    points:
      - id: point2
        position: reverse
    conflicts:
      - id: 3
      - id: 4
      - id: 5
      - id: 6
      - id: 7
  - id: 3 #route3
    source: signal4
    destination: signal6
    orientation: anticlockwise
    path:
      # point2.normal -> block5
      - id: seg8
      - id: seg9
      - id: seg10
      - id: seg11
    sections:
      - id: block5
    length: 107,60cm
    signals:
      - id: signal4
      - id: signal6
    points:
      - id: point2
        position: normal
    conflicts:
      - id: 2
      - id: 4
      - id: 6
  - id: 4 #route4
    source: signal5
    destination: signal3
    orientation: clockwise
    path:
      # point2.normal -> block2
      - id: seg8
      - id: seg7
      - id: seg6
      - id: seg5
    sections:
      - id: block2
    length: 96,35cm
    signals:
      - id: signal5
      - id: signal3
    points:
      - id: point2
        position: normal
    conflicts:
      - id: 2
      - id: 3
      - id: 6
  - id: 5 #route5
    source: signal7
    destination: signal9
    orientation: clockwise
    path:
      # point6.normal -> block1
      - id: seg21
      - id: seg20
      - id: seg19
      - id: seg18
    sections:
      - id: block1
    length: 82,10cm
    signals:
      - id: signal7
      - id: signal9
    points:
      - id: point6
        position: normal
    conflicts:
      - id: 0
      - id: 1
      - id: 2
      - id: 7
  - id: 6 #route6
    source: signal9
    destination: signal3
    orientation: clockwise
    path:
      # point2.reverse -> block2
      - id: seg8
      - id: seg7
      - id: seg6
      - id: seg5
    sections:
      - id: block2
    length: 96,35cm
    signals:
      - id: signal9
      - id: signal3
    points:
      - id: point2
        position: reverse
    conflicts:
      - id: 2
      - id: 3
      - id: 4
  - id: 7 #route7
    source: signal11
    destination: signal9
    orientation: clockwise
    path:
      # point6.reverse -> block1
      - id: seg21
      - id: seg20
      - id: seg19
      - id: seg18
    sections:
      - id: block1
    length: 82,10cm
    signals:
      - id: signal11
      - id: signal9
    points:
      - id: point6
        position: reverse
    conflicts:
      - id: 0
      - id: 1
      - id: 2
      - id: 5
